// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using T1708E.Models;

namespace T1708E.Migrations
{
    [DbContext(typeof(T1708EContext))]
    partial class T1708EContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("T1708E.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentRollNumber");

                    b.Property<int>("SubjectMark");

                    b.Property<string>("SubjectName");

                    b.HasKey("Id");

                    b.HasIndex("StudentRollNumber");

                    b.ToTable("Mark");

                    b.HasData(
                        new { Id = 1, StudentRollNumber = "D00469", SubjectMark = 10, SubjectName = "Java Core" },
                        new { Id = 2, StudentRollNumber = "D00529", SubjectMark = 7, SubjectName = "C#" },
                        new { Id = 3, StudentRollNumber = "D00553", SubjectMark = 8, SubjectName = "PHP" }
                    );
                });

            modelBuilder.Entity("T1708E.Models.Student", b =>
                {
                    b.Property<string>("RollNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("RollNumber");

                    b.ToTable("Student");

                    b.HasData(
                        new { RollNumber = "D00469", CreatedAt = new DateTime(2018, 11, 8, 19, 0, 11, 120, DateTimeKind.Local), Email = "admin@gmail.com", FirstName = "Duy", LastName = "Le", Status = 1, UpdatedAt = new DateTime(2018, 11, 8, 19, 0, 11, 122, DateTimeKind.Local) },
                        new { RollNumber = "D00529", CreatedAt = new DateTime(2018, 11, 8, 19, 0, 11, 123, DateTimeKind.Local), Email = "phuocding@gmail.com", FirstName = "Phuoc", LastName = "Nguyen", Status = 1, UpdatedAt = new DateTime(2018, 11, 8, 19, 0, 11, 123, DateTimeKind.Local) },
                        new { RollNumber = "D00553", CreatedAt = new DateTime(2018, 11, 8, 19, 0, 11, 123, DateTimeKind.Local), Email = "Vannhat@gmail.com", FirstName = "Nhat", LastName = "Nguyen", Status = 1, UpdatedAt = new DateTime(2018, 11, 8, 19, 0, 11, 123, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("T1708E.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("T1708E.Models.Mark", b =>
                {
                    b.HasOne("T1708E.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentRollNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
